#!/bin/sh

# do you even fmt bro?
# fail if gofmt has not been applied
list=$(gofmt -s -l .)

if [ -n "$list" ]; then
  echo Please apply gofmt and commit before pushing:
  printf "%s\n" $list
  exit 1
fi

# execute tests/lint/etc
find . -name go.mod -execdir sh -c '
  go test -cover ./... &&
  golangci-lint run' \;
